### PR TITLE
Fix #335, use browser.storage.local instead of browser.storage.sync

### LINKED ISSUE #328: An item stored using storage.sync may fails to sync because it exceeds the `QUOTA_BYTES_PER_ITEM` limit
This issue as been filed on bugzilla as
- [Bug 1484968 - Sync errors: extension-storage fails with "Insufficient Storage"](https://bugzilla.mozilla.org/show_bug.cgi?id=1484968)

From a brief look to the storage.sync API calls that are currently used in the side-view extensions, it seems that `desktopHostnames` is the only item that could grow in side until it reaches the `QUOTA_BYTES_PER_ITEM` limit (See [Bug 1484968 Comment 1](https://bugzilla.mozilla.org/show_bug.cgi?id=1484968#c1) and [Bug 1484968 Comment 3](https://bugzilla.mozilla.org/show_bug.cgi?id=1484968#c3)).

### LINKED ISSUE #332: Add-ons sync stopped
Hi,

After install this add-on(0.4.3710) the sync not working anymore.
 See the error:
`
1536936191398	Sync.Engine.Extension-Storage	WARN	Syncing failed: Error: HTTP 507 Insufficient Storage: Resource access is forbidden for this user (Maximum bytes per object exceeded (22031 > 16384 Bytes.)(resource://services-common/kinto-http-client.js:2341:5) JS Stack trace: ServerResponse@kinto-http-client.js:2341:5`

I think It's the size off add-on problem.. More detailed error below:
I'm using Latest Firefox nightly at Linux(Lubuntu equivalent)
https://github.com/wellington1993/MyFirefox

```
1536936190699	Sync.BulkKeyBundle	INFO	BulkKeyBundle being created for extension@bitly.com
1536936190699	Sync.CollectionKeyManager	INFO	Clearing collection keys...
1536936190699	Sync.CollectionKeyManager	INFO	Saving downloaded keys.
1536936190699	Sync.CollectionKeyManager	INFO	Bumping last modified to 1532528878831
1536936191398	Sync.Engine.Extension-Storage	ERROR	Syncing side-view@mozilla.org: request failed: Error: HTTP 507 Insufficient Storage: Resource access is forbidden for this user (Maximum bytes per object exceeded (22031 > 16384 Bytes.)(resource://services-common/kinto-http-client.js:2341:5) JS Stack trace: ServerResponse@kinto-http-client.js:2341:5
processResponse@kinto-http-client.js:2469:13
async*request@kinto-http-client.js:2521:14
async*execute@kinto-http-client.js:769:26
async*_batchRequests@kinto-http-client.js:685:33
async*batch@kinto-http-client.js:732:29
async*wrappedMethod@kinto-http-client.js:2931:18
batch@kinto-http-client.js:2191:12
async*pushChanges@kinto-offline-client.js:1805:26
async*sync@kinto-offline-client.js:1974:13
async*_syncCollection/<@ExtensionStorageSync.jsm:814:14
_requestWithToken@ExtensionStorageSync.jsm:825:20
async*_syncCollection@ExtensionStorageSync.jsm:806:12
sync@ExtensionStorageSync.jsm:744:27
async*syncAll/promises</<@ExtensionStorageSync.jsm:718:16
promise callback*syncAll/promises<@ExtensionStorageSync.jsm:717:63
syncAll@ExtensionStorageSync.jsm:716:22
async*_sync@extension-storage.js:38:12
async*WrappedNotify@util.js:179:27
1536936191398	Sync.Engine.Extension-Storage	WARN	Syncing failed: Error: HTTP 507 Insufficient Storage: Resource access is forbidden for this user (Maximum bytes per object exceeded (22031 > 16384 Bytes.)(resource://services-common/kinto-http-client.js:2341:5) JS Stack trace: ServerResponse@kinto-http-client.js:2341:5
processResponse@kinto-http-client.js:2469:13
async*request@kinto-http-client.js:2521:14
async*execute@kinto-http-client.js:769:26
async*_batchRequests@kinto-http-client.js:685:33
async*batch@kinto-http-client.js:732:29
async*wrappedMethod@kinto-http-client.js:2931:18
batch@kinto-http-client.js:2191:12
async*pushChanges@kinto-offline-client.js:1805:26
async*sync@kinto-offline-client.js:1974:13
async*_syncCollection/<@ExtensionStorageSync.jsm:814:14
_requestWithToken@ExtensionStorageSync.jsm:825:20
async*_syncCollection@ExtensionStorageSync.jsm:806:12
sync@ExtensionStorageSync.jsm:744:27
async*syncAll/promises</<@ExtensionStorageSync.jsm:718:16
promise callback*syncAll/promises<@ExtensionStorageSync.jsm:717:63
syncAll@ExtensionStorageSync.jsm:716:22
async*_sync@extension-storage.js:38:12
async*WrappedNotify@util.js:179:27
1536936191399	Sync.Status	DEBUG	Status for engine extension-storage: error.engine.reason.unknown_fail
1536936191399	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed_partial
1536936191399	Sync.ErrorHandler	DEBUG	extension-storage failed: Error: HTTP 507 Insufficient Storage: Resource access is forbidden for this user (Maximum bytes per object exceeded (22031 > 16384 Bytes.)(resource://services-common/kinto-http-client.js:2341:5) JS Stack trace: ServerResponse@kinto-http-client.js:2341:5
processResponse@kinto-http-client.js:2469:13
async*request@kinto-http-client.js:2521:14
async*execute@kinto-http-client.js:769:26
async*_batchRequests@kinto-http-client.js:685:33
async*batch@kinto-http-client.js:732:29
async*wrappedMethod@kinto-http-client.js:2931:18
batch@kinto-http-client.js:2191:12
async*pushChanges@kinto-offline-client.js:1805:26
async*sync@kinto-offline-client.js:1974:13
async*_syncCollection/<@ExtensionStorageSync.jsm:814:14
_requestWithToken@ExtensionStorageSync.jsm:825:20
async*_syncCollection@ExtensionStorageSync.jsm:806:12
sync@ExtensionStorageSync.jsm:744:27
async*syncAll/promises</<@ExtensionStorageSync.jsm:718:16
promise callback*syncAll/promises<@ExtensionStorageSync.jsm:717:63
syncAll@ExtensionStorageSync.jsm:716:22
async*_sync@extension-storage.js:38:12
async*WrappedNotify@util.js:179:27
1536936191401	Sync.Synchronizer	INFO	meta/global changed locally: reuploading.

```

I need to uninstall to make sync working, but waiting for help.
I like this idea.

Thanks!

### LINKED ISSUE #335: Turn off storage.sync
We don't really need to sync our data, and it's causing problems like #332. Let's just use `storage.local`

### PR DESCRIPTION
**Pull request by ianb**
This should also fix #332 and fix #328, as sync will no longer be an issue. We also clear any past sync storage to fix those issues for any existing users.

### CODE REVIEW

File: addon/background.js [hunk 1]
```diff
@@ -373,4 +373,10 @@ async function init() {
   }
 }
 
+// For somewhat unknown reasons we've caused sync probems for some users (probably because of too much data)
+// We've moved from browser.storage.sync to browser.storage.local to fix this.
+// BUT, existing users may still have too much data. This should clear it for them.
+// See also: https://github.com/mozilla/side-view/issues/332 and https://github.com/mozilla/side-view/issues/328
+browser.storage.sync.clear();
```
Comment (fzzzy) [inline addon/background.js]: Is this only going to clear side view's data?

**Comment by fzzzy** [comment]
Simple fix. r+ with fixed conflicts

File: addon/background.js (hunk 1 above)
Comment (ianb) [reply addon/background.js]: Yeah, that would be quite a security problem if one add-on could clear another's data!
