### PR TITLE
Fix #153, open sidebar from popup

### LINKED ISSUE #153: The sidebar does not open if you click any website from the Side View panel
[Affected versions]:
- Firefox 59.0.2 and up
- Side View 0.3.2.

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean Firefox profile with the latest Side View v0.3.2 installed.
- Have the Side View sidebar closed.
- Have one tab open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click the "Open Side View" toolbar button.
3. Select the website from the "Current Tabs" section and observe the behavior.

[Expected result]:
- The Side View sidebar is opened and the website is loaded in it.

[Actual result]:
- The sidebar does not open.

[Notes]:
- This issue is also reproducible with the website from the "Recent Tabs" section.
- Here is a screen recording with this issue: 
side view - closed sidebar

### PR DESCRIPTION
**Pull request by ianb**
- Also removes a bunch of messages/handlers that aren't applicable.
- Trim sidebar.js down to minimal code
- Send all requests to open pages to the background
- Cache known sidebar width for metrics

### CODE REVIEW

File: addon/sidebar.js [hunk 1]
```diff
@@ -1,26 +1,9 @@
...
-  args.cd1 = Math.round(window.innerWidth / 50) * 50;
-  args.type = "sendEvent";
-  browser.runtime.sendMessage(args);
-}
-
-function element(selector) {
-  return document.querySelector(selector);
-}
-
-element(".feedback-button").addEventListener("click", () => {
```
Comment (fzzzy) [inline addon/sidebar.js]: We actually still have the feedback button in the onboarding page, but I'm going to go ahead and merge this now since it is not hooked up to anything. When it is hooked up we will want to put this back, or maybe remove the feedback button from the onboarding page entirely.
